
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int parentesisCerrado = 15;
  public static final int muchasVeces = 25;
  public static final int dosPuntos = 18;
  public static final int barraO = 27;
  public static final int lanzamiento = 5;
  public static final int coma = 16;
  public static final int igual = 17;
  public static final int identificador = 21;
  public static final int terminal1 = 10;
  public static final int numeroEntero = 22;
  public static final int real = 8;
  public static final int caracter = 34;
  public static final int corcheteCerrado = 13;
  public static final int opcional = 24;
  public static final int extension = 6;
  public static final int parentesisAbierto = 14;
  public static final int EOF = 0;
  public static final int cadena1 = 9;
  public static final int noTerminal = 11;
  public static final int nombre = 2;
  public static final int error = 1;
  public static final int nuevaLinea = 31;
  public static final int entero = 7;
  public static final int espacioBlanco = 33;
  public static final int unoOmas = 26;
  public static final int autor = 4;
  public static final int letras = 30;
  public static final int numeros = 29;
  public static final int puntoComa = 19;
  public static final int corcheteAbierto = 12;
  public static final int numeroVersion = 23;
  public static final int texto = 35;
  public static final int ignorar = 28;
  public static final int separador = 20;
  public static final int version = 3;
  public static final int tabulador = 32;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "nombre",
  "version",
  "autor",
  "lanzamiento",
  "extension",
  "entero",
  "real",
  "cadena1",
  "terminal1",
  "noTerminal",
  "corcheteAbierto",
  "corcheteCerrado",
  "parentesisAbierto",
  "parentesisCerrado",
  "coma",
  "igual",
  "dosPuntos",
  "puntoComa",
  "separador",
  "identificador",
  "numeroEntero",
  "numeroVersion",
  "opcional",
  "muchasVeces",
  "unoOmas",
  "barraO",
  "ignorar",
  "numeros",
  "letras",
  "nuevaLinea",
  "tabulador",
  "espacioBlanco",
  "caracter",
  "texto"
  };
}

